### ISSUE TITLE
Waterfall

### ISSUE THREAD

**Issue by cwiese** [Imaginea/uvCharts#101]
Trying to make a Waterfall chart .... with Years on the X axis and 3 stacks for waterfall for EACH year...

This is not working.   There is only 1 bar per year .....how can I do this?

let graphDefinition = {
      categories : ['2014','2015','2016'],
      dataset : {
          '2014' : [
            { name : 'Oper Inc', value : 32 },
            { name : 'VBI', value : 60 },
            { name : 'Targ', value : 97 }
          ],
          '2015' : [
            { name : 'Oper Inc', value : 32 },
            { name : 'VBI', value : 60 },
            { name : 'Targ', value : 97 }
          ],
          '2016' : [
            { name : 'Oper Inc', value : 32 },
            { name : 'VBI', value : 60 },
            { name : 'Targ', value : 97 }
          ]
        }
      }

**Comment by hashd** [comment]
@cwiese, we do not have a multi category waterfall chart yet.

After you raised this issue I was wondering how would a multi category waterfall chart work like, 
https://community.qlik.com/servlet/JiveServlet/showImage/2-455442-52027/Overlapping+Waterfalls.png

http://1.bp.blogspot.com/-8Q4QPAhF5Hg/TdAXjYgR0cI/AAAAAAAAEQQ/efqhetfKFXQ/s1600/stacked-waterfall.png

Let me know which one of these 2 suits your requirement

**Comment by cwiese** [comment]
This is the format

**Comment by hashd** [comment]
Thanks, will update the issue and will get back to you after the weekend.

**Comment by cwiese** [comment]
You completely rock.  "Waterfall" is beyond many libraries like C3.js

**Comment by cwiese** [comment]
So - is "multi-series" possible?  Do I need to switch to another library for a demo we have coming up Thursday?  Thanks.

**Comment by hashd** [comment]
@cwiese, I will let you know in about 10 hours from now. It should be possible as per the screens you have provided. Been occupied with other work in the last few days

**Comment by cwiese** [comment]
Thank you much.

**Comment by hashd** [comment]
I had to create a new chart type to support your requirement over here. Just check it out and let me know if this is good. In the meantime, I will run more test cases on this. 

The new chart type will have the key 'StepUpWaterfall' similar to 'StepUpBar' but this will handle negative values.

![stepupwaterfall](https://cloud.githubusercontent.com/assets/945317/8799960/255a88d8-2fcc-11e5-9b09-6d2ffa11c584.png)

**Comment by cwiese** [comment]
Very cool - I do believe this will work.

**Comment by hashd** [comment]
@cwiese Do let me know if things are fine on your end, otherwise I'll mark the release stable tomorrow

**Comment by cwiese** [comment]
So far it is working great!

Question: There is no need to destroy() a chart we using something like ember and we navigate to a new view? We do this with C3.js?

**Comment by hashd** [comment]
You could do it using the remove function on the chart instance

```
var chart = uv.chart('Bar', graphdef);
.............

chart.remove()
```

It's not necessary if you're clearing the DOM already.

**Comment by hashd** [comment]
I'm marking the release stable and closing this issue.
