### ISSUE TITLE
Ability to format value labels using configuration

### ISSUE THREAD

**Issue by cwiese** [Imaginea/uvCharts#107]
Looking great.

Two questions: 

1. How to format label (commas or in Millions) 
2. How to make legend labels wider (they over lap) 

![image](https://cloud.githubusercontent.com/assets/178527/8840685/bdbc1f2e-30b2-11e5-9786-4277b5614726.png)

**Comment by hashd** [comment]
At the moment, we don't have ability to do that. But I'll make it as a configurable property in one of the point releases soon.

**Comment by hashd** [comment]
As in the image, we do not have support for negative axes yet :( and we're targeting it to be a part of 1.1.0.

**Comment by cwiese** [comment]
I am not concerned about the axes ..

1. the legend overlaps 
2. so I will need to hack to make the Data Label value have thousand's separator?

**Comment by hashd** [comment]
I can provide you support by EOD tomorrow for custom labels and more wider legend labels.

**Comment by cwiese** [comment]
I have a demo at 11:00 EST.  

Would I format the value at this line? 

https://github.com/Imaginea/uvCharts/blob/master/src/gfx/stepup_waterfall.js#L71 <https://github.com/Imaginea/uvCharts/blob/master/src/gfx/stepup_waterfall.js#L71>

Thanks Kiran!

**Comment by hashd** [comment]
Yeah, you can edit that part of the code to meet your needs.
