### ISSUE TITLE
StepUpWaterFall 

### ISSUE THREAD

**Issue by cwiese** [Imaginea/uvCharts#108]
dimension height in config is ignored ...still at 500

      dimension : {
        width : 1000,
        height : 300
      },

**Comment by hashd** [comment]
Height of the chart (svg element) will be equal to dimension.height + margin.top + margin.bottom. Let me know if its not matching even after that because I would be surprised if so :)

**Comment by hashd** [comment]
Marking this invalid until proven wrong :)
