### ISSUE TITLE
StepUpWaterFall

### ISSUE THREAD

**Issue by cwiese** [Imaginea/uvCharts#111]
Is this possible with StepUpWaterFall.

Not that this "Steps Up", shows the TOTAL and then "Steps Down" to the TOTAL remaining 

![image](https://cloud.githubusercontent.com/assets/178527/8870665/af4ed42a-31bd-11e5-9cea-ab9d12b5bff0.png)

**Comment by hashd** [comment]
Generalizing this for more use cases would be difficult, we'll need to think more about this before I can give you an answer.

**Comment by cwiese** [comment]
We are seeing this chart variation in many places .... I can send links 

It seems we'd need to be able to indicates we the step up resets to zero ? 

Thanks, Chuck

**Comment by hashd** [comment]
Thanks, this looks like a good approach to do it without affecting other charts. I will mark this as a task for us.

**Comment by hashd** [comment]
StepUpBar chart would be able to support such requirement from 1.1.0 onwards
