### ISSUE TITLE
Scale and two type of graph

### ISSUE THREAD

**Issue by mtkilic** [Imaginea/uvCharts#163]
I know there is scale for sqrt, pow and log, is there one for percentage I would like change my scale of y-axis to percentage for StackedBar

Second question is it possible to add a line graph to my StackedBar?

thanks

**Comment by hashd** [comment]
We do not have a percentage scale at the moment. With a bit of code, you can calculate the percentages before u create the chart. I can create a fiddle for you if you can provide me the code.

We do not have hybrid charts, we don't plan upon supporting them in uvCharts 1.x.x series

**Comment by mtkilic** [comment]
Sorry for the late response. I change dataset to what you guys had on website. 
There is couple things I am trying to accomplish with this graph

- Make scale to %, even when hover over bar
-I like make drop down menu with couple selection, so graph will change what is in that data.
- Lastly, data range filter to support chart

I will much appreciate if you can help me with this. Or even give me a feedback where I can take look to make this work.

Thank you

```
<html>
<head>

  <script src='vendor/d3.min.js'></script>
  <script src='vendor/uvcharts.min.js'></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.2.2/d3.v3.min.js"></script>
  <script type="text/javascript">
    var init = function() {

  var graphdef = {
  categories : ['uvCharts', 'Matisse', 'SocialByWay'],
  dataset : {
    'uvCharts' : [
      { name : '2008', value: 15},
      { name : '2009', value: 28},
      { name : '2010', value: 42},
      { name : '2011', value: 88},
      { name : '2012', value: 100},
      { name : '2013', value: 143}
    ],
    'Matisse' : [
      { name : '2008', value: 15},
      { name : '2009', value: 28},
      { name : '2010', value: 42},
      { name : '2011', value: 88},
      { name : '2012', value: 100},
      { name : '2013', value: 143}
    ],  
    'SocialByWay' : [
      { name : '2008', value: 15},
      { name : '2009', value: 28},
      { name : '2010', value: 42},
      { name : '2011', value: 88},
      { name : '2012', value: 100},
      { name : '2013', value: 143}
    ]
  }
};

      var config = {

        graph : {
          orientation : 'Vertical',
          custompalette : ['#A1A4A5', '#C80F98','#5F0DCF']


        },

        meta : {
          position : '#uv-div',
          caption : 'Usage of open source projects',
          subcaption : 'For the last 5 years',
          hlabel : 'Year',
          vlabel : 'Share',

          
        },
      

        legend : {
          position: 'right'
        },
        dimension : {
          width : '800',
          height : '500'
        },
        scale :{
          type : 'linear',
          ordinality : '0.1',
        }
      };

      var charObject = uv.chart('StackedBar', graphdef, config);
    };
  </script>
 

</head>
<body onload='init()'>
<div id='uv-div'></div>
</body>
</html> 
```

**Comment by hashd** [comment]
@mtkilic have you tried using 'PercentBar' chart? It might be what you're searching for.

**Comment by mtkilic** [comment]
@hashd StackedBar works perfectly at the moment. All I want to try to do now is, Change dataset(graph) based on drop down menu selection.

I have updated my code on previous comment. now there is Dropdown menu. Can you help me get that working? Or is this even possible to do with uvCharts?

**Comment by hashd** [comment]
@mtkilic There is no provision for you to change the dataset once set for a particular chart. You could however remove the previous chart and create a new one using the new dataset. Would that work for you?

**Comment by mtkilic** [comment]
@hashd I think so, but if you don't mind can you show me and example on fiddle please.

**Comment by hashd** [comment]
This is a rather naive fiddle.

https://jsfiddle.net/t06vz2ea/4/

Builds a chart, removes it in a second and creates another one after couple of seconds.

**Comment by mtkilic** [comment]
@hashd thats not quite what I need. I like that feature but I am looking tame something similar to this. http://bl.ocks.org/anupsavvy/9513382 Whenever you select different date from dropdown chart change accordingly to that data.

**Comment by hashd** [comment]
@mtkilic Sorry, we do not support transitions on data or chart type change. Its a known limitation.
