### ISSUE TITLE
Bower.json outdated

### ISSUE THREAD

**Issue by gempain** [Imaginea/uvCharts#170]
Hello,

The bower.json seems to be outdated since there is no package named "uvCharts" in the bower repository.

All the best.

**Comment by hashd** [comment]
We haven't published uvCharts on bower. I guess it makes sense to do. I'll update you once done.

**Comment by gempain** [comment]
It does make much sense, since most developers use it. There is a `bower.json` file in the repo, which isn't set as private, so I assumed the project was published on bower.

Looking forward for the update. Thanks a lot !

**Comment by hashd** [comment]
Just published the package on bower.

`bower info uvCharts`
