### ISSUE TITLE
config.graph.custompalette is undefined

### ISSUE THREAD

**Issue by abrice** [Imaginea/uvCharts#76]
I have a prototype added to array:
Array.prototype.strUnique2 = function(infieldname) {
    var o = {}, i, l = this.length, r = [];
    for(i=0; i<l;i++) o[this[i][infieldname]] = null;
    for(i in o) r.push(i);
    return r;
};

If I include this then the uvchart draw fails using your basic example:
    var graphdef = {
    categories : ['uvCharts'],
    dataset : {
        'uvCharts' : [
            { name : '2009', value : 32 },
            { name : '2010', value : 60 },
            { name : '2011', value : 97 },
            { name : '2012', value : 560 },
            { name : '2013', value : 999 }
        ]
    }
}
    var chart = uv.chart('Bar', graphdef);

then uvcharts fails with: config.graph.custompalette is undefined

If I remove the Array.prototype then it works.
How come, they don't look related?

By the way, have you stopped work on the library or is it still under development?
Thanks,
Andrew

**Comment by cwiese** [comment]
I have this same custompalette issue ( config.graph.custompalette is undefined) ...

I cloned and grunt build ....but the version still has the issue ....how can I get 1.1.0?    do I need to git pull a version? how?

**Comment by hashd** [comment]
@cwiese 1.1.0 will be made available in August. In the meanwhile, I'll try to release a bugfix release for this particular issue.

It would be helpful if you could provide me little insight to what you're trying to do. Code samples would be great.

**Comment by hashd** [comment]
@cwiese Could you try this bugfix release and let me know if this fixes the issue for you. I have tested it for @abrice's case and it works fine.

**Comment by cwiese** [comment]
That fixed it ....however, does this release change something?  My chart is sized very small by default.


![image](https://cloud.githubusercontent.com/assets/178527/8719999/cfb58aa6-2b7d-11e5-8b27-32fb1484202c.png)

**Comment by hashd** [comment]
Yeah, we have initial support for responsiveness in this release, it'll take the width and height of the parent container.

I'll disable responsiveness until 1.1.0 and provide you an updated release

**Comment by cwiese** [comment]
Thank you so much.  (responsive sounds great - would I wrap in a “explicitly sized” div to make it work?)

**Comment by hashd** [comment]
Yes, that would work

**Comment by cwiese** [comment]
I can not seem to make that work.

**Comment by hashd** [comment]
try adding this property to your stylesheet

``` css
.uv-chart-div {
  width: 500px;
  height: 500px;
}
```

**Comment by cwiese** [comment]
Hmmm.  Every chart in our app may be a different size.  I was using c3.js but they lack a waterfall.

**Comment by hashd** [comment]
That makes sense. I'll have to consider that before considering responsiveness stable.

Please do try this release: https://github.com/hashd/uvCharts/raw/master/dist/uvcharts-1.0.2.zip

The revised release 1.0.2 has responsiveness disabled by default. We'll make 'Responsiveness' default in 1.1.0 release.

**Comment by cwiese** [comment]
perfect and thank you

**Comment by cwiese** [comment]
is there a Chart.resize function that I can call when the viewport changes?

**Comment by hashd** [comment]
@cwiese we do not have support for that at the moment and that is why we are trying to bring in responsiveness as part of the library.

You could try the 1.0.3 version (which will be put up in the next 10 minutes) which will potentially serve your need here
