### ISSUE TITLE
#Question: How to enable responsive ?

### ISSUE THREAD

**Issue by karthikeyanthangavel** [Imaginea/uvCharts#77]

**Comment by hashd** [comment]
Hi Karthikeyan,

We haven't thought of responsiveness in the initial design so its not available in the current release. We'll keep it in mind while working on further releases.

**Comment by hashd** [comment]
@karthikeyanthangavel I have been trying to enable responsive charts for this library and wanted to check with you on your requirement. If you could elaborate more on how you would like it to work, that would be pretty helpful to me

**Comment by hashd** [comment]
Version 1.0.3 and above have responsiveness, but you'll need to enable it using the following config within your chart configuration

``` json
config = {
     graph : {
           responsive: true
      }
}
```
