### ISSUE TITLE
legend

### ISSUE THREAD

**Issue by Corobori** [Imaginea/uvCharts#78]
In the documentation it says for legend " All properties related to the legend of the chart" but none are listed. Is there a way not to display a legend ? 
uv-panel appears to consider the legend in calculating the height and it takes a lot of space.

**Comment by hashd** [comment]
Add following configuration to your config object and Legends will not be rendered.

```
legend: {
   showlegends: false
}
```

**Comment by hashd** [comment]
creating a new issue regarding the documentation part
