### ISSUE TITLE
Reg AngularJs directives for uvCharts

### ISSUE THREAD

**Issue by smart987** [Imaginea/uvCharts#81]
Hi Imaginea, Nice charts library. Do you have any plans to release the Angularjs directives for these charts?

**Comment by hashd** [comment]
Thanks for showing interest in uvCharts.

Angular directives for uvCharts does sound interesting and aligns with our goal of making charting an easy task for other developers. I'll have to assess the feasibility and timelines.

**Comment by smart987** [comment]
Another nice feature that makes uVCharts unique to other charting libraries is, it should be easily customizable to add any type of new chart from the official D3.js website. This is what most of the charting libraries are lacking right now. For example if I want to have Sun Burst chart (http://bl.ocks.org/mbostock/4348373) using uvChart, is it possible to accomplish it?

**Comment by hashd** [comment]
Marking this as a sub part of #114
